import { network, injected, uauth, walletconnect, walletlink } from 'connectors'

export const SUPPORTED_WALLETS = {
  PROXY: {
    id: 'proxy',
    connector: network,
    name: 'Proxy Wallet',
    caption: 'Proxy Wallet',
    iconProps: { collection: 'yolorekt', name: 'moon' },
    description: 'Proxy wallet',
    url: '',
    dappDeepLinkTemplate: null,
    color: '#12203C',
    mobile: false,
    desktop: false,
    showInBrowsers: ['all']
  },
  INJECTED: {
    id: 'injected',
    connector: injected,
    name: 'Injected',
    caption: 'Injected',
    iconProps: { collection: 'crypto', name: 'moon' },
    description: 'Injected web3 provider.',
    dappDeepLinkTemplate: null,
    color: '#010101',
    primary: true,
    mobile: false,
    desktop: false,
    showInBrowsers: ['all']
  },
  BRAVE: {
    id: 'brave',
    connector: injected,
    name: 'Brave Wallet',
    caption: 'Brave Wallet',
    iconProps: { collection: 'crypto', name: 'brave' },
    description: 'Easy-to-use browser extension.',
    url: 'https://brave.com/',
    dappDeepLinkTemplate: null,
    color: '#E8831D',
    mobile: false,
    desktop: true,
    showInBrowsers: ['brave']
  },
  METAMASK: {
    id: 'metamask',
    connector: injected,
    name: 'MetaMask',
    caption: 'MetaMask',
    iconProps: { collection: 'crypto', name: 'metamask' },
    description: 'Easy-to-use browser extension.',
    url: 'https://metamask.io/',
    dappDeepLinkTemplate: null,
    color: '#E8831D',
    mobile: false,
    desktop: true,
    showInBrowsers: ['all']
  },
  METAMASK_BROWSER: {
    id: 'metamask',
    connector: injected,
    name: 'MetaMask browser',
    caption: 'MetaMask',
    iconProps: { collection: 'crypto', name: 'metamaskBrowser' },
    url: 'https://metamask.io/',
    dappDeepLinkTemplate: `https://metamask.app.link/dapp/{dappURL}`,
    color: '#E8831D',
    mobile: true,
    desktop: false,
    showInBrowsers: ['all']
  },
  WALLET_CONNECT: {
    id: 'walletConnect',
    connector: walletconnect,
    name: 'WalletConnect',
    caption: 'WalletConnect',
    iconProps: { collection: 'crypto', name: 'walletConnect' },
    description: 'Connect to Trust Wallet, Rainbow Wallet and more...',
    url: 'https://walletconnect.org/',
    dappDeepLinkTemplate: null,
    color: '#4196FC',
    mobile: true,
    desktop: true,
    showInBrowsers: ['all']
  },
  UNSTOPPABLE_DOMAINS: {
    id: 'unstoppable',
    connector: uauth,
    name: 'Unstoppable Domains',
    caption: 'Unstoppable Domains',
    iconProps: { collection: 'crypto', name: 'unstoppableDomain' },
    description: 'Use Untoppable Domains with us',
    dappDeepLinkTemplate: null,
    color: 'rgb(80,72,248)',
    mobile: false,
    desktop: true,
    showInBrowsers: ['all']
  },
  WALLET_LINK: {
    id: 'walletLink',
    connector: walletlink,
    name: 'Coinbase Wallet',
    caption: 'Coinbase Wallet',
    iconProps: { collection: 'crypto', name: 'coinbaseWallet' },
    description: 'Use Coinbase Wallet app on mobile device',
    dappDeepLinkTemplate: null,
    color: '#315CF5',
    mobile: false,
    desktop: false,
    showInBrowsers: ['all']
  },
  COINBASE_LINK: {
    id: 'coinbaseLink',
    name: 'Open in Coinbase Wallet',
    caption: 'Open in Coinbase Wallet',
    iconProps: { collection: 'crypto', name: 'moon' },
    description: 'Open in Coinbase Wallet app.',
    dappDeepLinkTemplate: 'https://go.cb-w.com/mtUDhEZPy1', //ACZ --> Hands Up!!!, may be needs a register
    color: '#315CF5',
    mobile: false,
    desktop: false,
    showInBrowsers: ['all']
  },
  FORTMATIC: {
    id: 'formatic',
    connector: null,
    name: 'Fortmatic',
    caption: 'Fortmatic',
    iconProps: { collection: 'crypto', name: 'moon' },
    description: 'Login using Fortmatic hosted wallet',
    dappDeepLinkTemplate: null,
    color: '#6748FF',
    mobile: false,
    desktop: false,
    showInBrowsers: ['all']
  },
  PORTIS: {
    id: 'portis',
    connector: null,
    name: 'Portis',
    caption: 'Portis',
    iconProps: { collection: 'crypto', name: 'moon' },
    description: 'Login using Portis hosted wallet',
    dappDeepLinkTemplate: null,
    color: '#4A6C9B',
    mobile: false,
    desktop: false,
    showInBrowsers: ['all']
  }
}
